// Generated by Report Card Enterprise v7.4.0.
window.RCE_CONFIG = Object.freeze({
  supabaseUrl: "https://gmbchwvvdwulolgtsnfs.supabase.co",
  supabaseAnonKey: "sb_publishable_23OGcL-wAoIpmK6JFrXjuQ_9tLIQQSR",
  productName: "Report Card Enterprise",
  productShortName: "RCE",
  productTagline: "School Report Card and Academic Records System",
  productLogoPath: "assets/rce-master-logo.png",
  masterEdition: false,
  appName: "Nipe International School Report Card System",
  schoolName: "Nipe International School",
  schoolShortName: "Nipe Reports",
  userEmailDomain: "nip.app",
  reportNumberPrefix: "NIS",
  generatedSchoolPackage: true,
  tenantCode: "N-001",
  packageId: "0445423a-34d5-421b-9f84-3d255d0c2fdd",
  installationId: "4ad797c0-5b99-484f-ba93-30581945f838",
  projectRef: "gmbchwvvdwulolgtsnfs",
  authorizedDomain: "nduah89.github.io",
  licenseKeyId: "rce-p256-47297bd25be320b495c3",
  logoPath: "assets/school-logo.png",
  defaultReportTemplatePath: "assets/approved-terminal-report-template.png"
});
window.NIS_CONFIG = window.RCE_CONFIG;
